server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///D:/ENSET/S5/Systèmes Distribués et Big Data Processing/projects_new_folder/config-repo
    # disable consul
    consul:
      discovery:
        enabled: false
